language: ruby
sudo: false
rvm:
  - 2.3.4
  - 2.4.2
  - 2.5.0
gemfile:
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.gemfile
  - gemfiles/rails_4.2.gemfile
services:
 - redis-server
env:
  - LIT_STORAGE=hash
  - LIT_STORAGE=redis
before_script:
  - cp test/dummy/config/database.yml.travis test/dummy/config/database.yml
  - psql -c 'create database lit_test;' -U postgres
  - RAILS_ENV=test bundle exec rake db:migrate
script: "bundle exec rake test"
